---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'
    
- name: start nginx server
  docker_container:
    name: nginx
    image: nginx
    ports:
      - 8080:80