# tasks file for docker
- name: uninstall docker
  yum: 
    name: 
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc
    state: absent

- name: update https
  yum: 
    name:
    - yum-utils
    update_cache: yes
    state: present


- name: Add stable repository
  yum_repository:
    name: epel
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    description: docker YUM repo

- name: Install Docker
  yum: 
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present
    update_cache: yes
  notify: 
  - restart docker

- name: install docker-py
  pip:
    name: docker-py

- name: Add ec2-user user to docker group
  user:
    name: ec2-user
    group: docker