# tasks file for docker
- name: uninstall docker
  apt: 
    pkg: 
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc
    state: absent

- name: update https
  apt: 
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip
    update_cache: yes
    state: present

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add stable repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker
  apt: 
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present
    update_cache: yes
  notify: 
  - restart docker

- name: install docker-py
  pip:
    name: docker-py

- name: Add ubuntu user to docker group
  user:
    name: "{{ item }}"
    group: docker
  with_items: "{{ debain_users }}"