---
- name: install docker
  hosts: _Role_web
  remote_user: ubuntu
  become: yes

  tasks:
  - name: uninstall docker
    apt: 
      pkg: 
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
      state: absent

  - name: update https
    apt: 
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-pip
      state: present

  - name: Add Docker’s official GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add stable repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Install Docker
    apt: 
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: present
      update_cache: yes
    notify: 
    - restart docker

  - name: install docker-py
    pip:
      name: docker-py

  - name: Add ubuntu user to docker group
    user:
      name: ubuntu
      group: docker

  - name: start nginx server
    docker_container:
      name: nginx
      image: nginx
      ports:
        - 8080:80

  handlers:
    - name: restart docker
      ansible.builtin.service:
        name: docker
        state: restarted