---
plugin: aws_ec2
## no need for keys using roles on the master machine
#aws_access_key: <access was key>
#aws_secret_key: <secret was key>
keyed_groups:
  - key: tags
    #    prefix: web

hostnames:
  - private-ip-address

# /opt/ansible/inventory/aws_ec2.yaml